/* Generated by RuntimeBrowser
   Platform: iOS 15.7.3 (19H307) arm64
   Image: /System/Library/Frameworks/Speech.framework/Speech (1)
 */

@interface _SFSearchResult : NSObject {
    NSData * _data;
    NSHTTPURLResponse * _response;
    long long  _searchType;
}

@property (nonatomic, readonly) NSData *data;
@property (nonatomic, readonly) NSHTTPURLResponse *response;
@property (nonatomic, readonly) long long searchType;

- (void).cxx_destruct;
- (id)data;
- (id)description;
- (id)initWithVoiceSearchResult:(id)arg1;
- (id)response;
- (long long)searchType;

@end
