/* Generated by RuntimeBrowser
   Platform: iOS 14.2 (18B111) arm64
   Image: /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox (1.8)
 */

@interface AVHapticParameterCurveValue : NSObject {
    double  _time;
    float  _value;
}

@property double time;
@property float value;

- (void)setTime:(double)arg1;
- (void)setValue:(float)arg1;
- (double)time;
- (float)value;

@end
