/* Generated by RuntimeBrowser
   Platform: iOS 15.7.3 (19H307) arm64
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome (1)
 */

@interface SBClusteredPlaceholderIcon : SBPlaceholderIcon

- (bool)isClusteredIconPlaceholder;

@end
