/* Generated by RuntimeBrowser
   Platform: iOS 15.7.2 (19H218) arm64
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome (1)
 */

@interface SBFloatingDockIconListView : SBDockIconListView

- (void)configureIconView:(id)arg1 forIcon:(id)arg2;

@end
