/* Generated by RuntimeBrowser
   Platform: iOS 15.7.2 (19H218) arm64
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome (1)
 */
//the classes in instance methods were filled in by me best guess at logical class but you can use 'id' to be sure

@interface SBHCustomIconListLayoutProvider : NSObject <SBIconListLayoutProvider> {
    <SBIconListLayout> * _defaultLayout;
    NSDictionary * _listLayouts;
}

@property (nonatomic, readonly) <SBIconListLayout> *defaultLayout;
@property (nonatomic, readonly, copy) NSDictionary *listLayouts;

- (void).cxx_destruct;
- (SBIconListLayout *)defaultLayout;
- (id)init;
- (id)initWithListLayouts:(NSDictionary *)listLayouts;
- (id)initWithListLayouts:(NSDictionary *)listLayouts defaultLayout:(SBIconListLayout*)defaultLayout;
//a whole tweak coukld be built around this using 
- (SBIconListLayout *)layoutForIconLocation:(NSString *location)arg1;
- (NSDictionary *)listLayouts;

@end
