/* Generated by RuntimeBrowser
   Platform: iOS 15.7.3 (19H307) arm64
   Image: /System/Library/PrivateFrameworks/SpringBoardUI.framework/SpringBoardUI (1.0)
 */

@interface SBLockScreenLegibilitySettings : _UILegibilitySettings {
    UIColor * _backgroundColorHint;
    bool  _vibrancyDisabled;
}

@property (nonatomic, retain) UIColor *backgroundColorHint;
@property (nonatomic) bool vibrancyDisabled;

+ (id)defaultSettings;

- (void).cxx_destruct;
- (id)backgroundColorHint;
- (void)setBackgroundColorHint:(id)arg1;
- (void)setVibrancyDisabled:(bool)arg1;
- (bool)vibrancyDisabled;

@end
