/* Generated by RuntimeBrowser
   Platform: iOS 15.7.3 (19H307) arm64
   Image: /System/Library/Frameworks/Speech.framework/Speech (1)
 */

@interface SFSpeechURLRecognitionRequest : SFSpeechRecognitionRequest {
    NSURL * _URL;
}

@property (nonatomic, readonly, copy) NSURL *URL;

- (void).cxx_destruct;
- (id)URL;
- (void)_handlePreRecordedAudioWithAsset:(id)arg1 audioTracks:(id)arg2 narrowband:(bool)arg3 addSpeechDataBlock:(id /* block */)arg4 stopSpeechBlock:(id /* block */)arg5 cancelSpeechWithErrorBlock:(id /* block */)arg6;
- (id)_startedConnectionWithLanguageCode:(id)arg1 delegate:(id)arg2 taskHint:(long long)arg3 requestIdentifier:(id)arg4;
- (id)_startedLocalConnectionWithLanguageCode:(id)arg1 delegate:(id)arg2 taskHint:(long long)arg3 requestIdentifier:(id)arg4;
- (id)init;
- (id)initWithURL:(id)arg1;

@end
